/**
 * Complete list of all available OfficeRnD Flex API OAuth2 scopes.
 * Used by the "Add All Scopes" command to populate the scopes configuration.
 */
export const ALL_SCOPES: readonly string[] = [
  // Billing — Payments
  'flex.billing.payments.read',
  'flex.billing.payments.create',
  'flex.billing.payments.methods.read',
  'flex.billing.payments.documents.read',
  'flex.billing.payments.update',
  'flex.billing.payments.allocations.update',
  'flex.billing.payments.allocations.create',
  // Billing — Charges
  'flex.billing.charges.read',
  'flex.billing.charges.create',
  'flex.billing.charges.update',
  'flex.billing.charges.delete',
  // Billing — Checkout & Tax
  'flex.billing.checkout.create',
  'flex.billing.taxRates.read',
  'flex.billing.revenueAccounts.read',
  'flex.billing.plans.read',
  'flex.billing.resourceRates.read',
  'flex.billing.cancellationPolicies.read',
  // Billing — Payment Details & Gateways
  'flex.billing.paymentDetails.read',
  'flex.billing.paymentDetails.create',
  'flex.billing.paymentDetails.delete',
  'flex.billing.paymentGateways.authorize',
  // Space — Bookings
  'flex.space.bookings.read',
  'flex.space.bookings.validate',
  'flex.space.bookings.create',
  'flex.space.bookings.update',
  'flex.space.bookings.delete',
  'flex.space.bookings.cancel',
  // Space — Locations & Structure
  'flex.space.locations.read',
  'flex.space.floors.read',
  'flex.space.resources.read',
  'flex.space.resourceTypes.read',
  // Space — Assignments & Passes
  'flex.space.assignments.read',
  'flex.space.assignments.create',
  'flex.space.assignments.delete',
  'flex.space.amenities.read',
  'flex.space.passes.read',
  'flex.space.passes.create',
  'flex.space.passes.update',
  'flex.space.passes.delete',
  // Space — Credits & Coins
  'flex.space.credits.read',
  'flex.space.credits.create',
  'flex.space.credits.update',
  'flex.space.credits.delete',
  'flex.space.coins.read',
  // Collaboration — Tickets
  'flex.collaboration.tickets.read',
  'flex.collaboration.tickets.create',
  'flex.collaboration.tickets.update',
  'flex.collaboration.ticketOptions.read',
  'flex.collaboration.ticketComments.read',
  'flex.collaboration.ticketComments.create',
  // Collaboration — Posts & Events
  'flex.collaboration.posts.read',
  'flex.collaboration.posts.create',
  'flex.collaboration.posts.delete',
  'flex.collaboration.events.read',
  'flex.collaboration.events.create',
  'flex.collaboration.events.update',
  'flex.collaboration.events.delete',
  'flex.collaboration.benefits.read',
  // Community — Members & Companies
  'flex.community.members.read',
  'flex.community.members.create',
  'flex.community.members.update',
  'flex.community.members.delete',
  'flex.community.members.portalAccess.update',
  'flex.community.companies.read',
  'flex.community.companies.create',
  'flex.community.companies.update',
  'flex.community.companies.delete',
  // Community — Visits & Visitors
  'flex.community.visits.read',
  'flex.community.visits.create',
  'flex.community.visits.delete',
  'flex.community.visitors.read',
  'flex.community.visitors.create',
  'flex.community.visitors.delete',
  // Community — Opportunities & Contracts
  'flex.community.opportunities.read',
  'flex.community.opportunities.create',
  'flex.community.opportunities.update',
  'flex.community.opportunities.delete',
  'flex.community.opportunityStatuses.read',
  'flex.community.contracts.read',
  'flex.community.contracts.update',
  'flex.community.contracts.create',
  'flex.community.contracts.delete',
  'flex.community.contracts.sign',
  'flex.community.contracts.terminate',
  // Community — Check-ins, Fees & Memberships
  'flex.community.checkins.read',
  'flex.community.checkins.create',
  'flex.community.checkins.update',
  'flex.community.fees.read',
  'flex.community.fees.create',
  'flex.community.fees.update',
  'flex.community.fees.delete',
  'flex.community.memberships.read',
  'flex.community.memberships.create',
  'flex.community.memberships.update',
  'flex.community.memberships.delete',
  'flex.community.receptionFlows.read',
  // Settings
  'flex.settings.webhooks.read',
  'flex.settings.webhooks.create',
  'flex.settings.webhooks.update',
  'flex.settings.webhooks.delete',
  'flex.settings.customProperties.read',
  'flex.settings.secondaryCurrencies.read',
  'flex.settings.secondaryCurrencies.update',
  'flex.settings.billing.read',
  'flex.settings.integrations.read',
  'flex.settings.businessHours.read',
  'flex.settings.organization.read',
  // User auth
  'flex.user.auth.signup',
  'flex.user.auth.signin',
  'flex.user.auth.impersonate',
  'flex.user.auth.verify',
  'flex.user.password.update',
];
